/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenueRouteImport } from './routes/venue'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SpeakersRouteImport } from './routes/speakers'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ProjectExhibitionRouteImport } from './routes/project-exhibition'
import { Route as N30RouteImport } from './routes/n30'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MascotRouteImport } from './routes/mascot'
import { Route as HighlightsRouteImport } from './routes/highlights'
import { Route as HackathonRouteImport } from './routes/hackathon'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShowcaseRegisterRouteImport } from './routes/showcase.register'
import { Route as ProjectExhibitionRegisterRouteImport } from './routes/project-exhibition.register'
import { Route as HackathonRegisterRouteImport } from './routes/hackathon.register'
import { Route as ApiN30ChatRouteImport } from './routes/api/n30-chat'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const VenueRoute = VenueRouteImport.update({
  id: '/venue',
  path: '/venue',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersRoute = SpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectExhibitionRoute = ProjectExhibitionRouteImport.update({
  id: '/project-exhibition',
  path: '/project-exhibition',
  getParentRoute: () => rootRouteImport,
} as any)
const N30Route = N30RouteImport.update({
  id: '/n30',
  path: '/n30',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MascotRoute = MascotRouteImport.update({
  id: '/mascot',
  path: '/mascot',
  getParentRoute: () => rootRouteImport,
} as any)
const HighlightsRoute = HighlightsRouteImport.update({
  id: '/highlights',
  path: '/highlights',
  getParentRoute: () => rootRouteImport,
} as any)
const HackathonRoute = HackathonRouteImport.update({
  id: '/hackathon',
  path: '/hackathon',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRegisterRoute = ShowcaseRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => ShowcaseRoute,
} as any)
const ProjectExhibitionRegisterRoute =
  ProjectExhibitionRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => ProjectExhibitionRoute,
  } as any)
const HackathonRegisterRoute = HackathonRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => HackathonRoute,
} as any)
const ApiN30ChatRoute = ApiN30ChatRouteImport.update({
  id: '/api/n30-chat',
  path: '/api/n30-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/hackathon': typeof HackathonRouteWithChildren
  '/highlights': typeof HighlightsRoute
  '/mascot': typeof MascotRoute
  '/mcp': typeof McpRoute
  '/n30': typeof N30Route
  '/project-exhibition': typeof ProjectExhibitionRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/showcase': typeof ShowcaseRouteWithChildren
  '/speakers': typeof SpeakersRoute
  '/sponsors': typeof SponsorsRoute
  '/venue': typeof VenueRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/n30-chat': typeof ApiN30ChatRoute
  '/hackathon/register': typeof HackathonRegisterRoute
  '/project-exhibition/register': typeof ProjectExhibitionRegisterRoute
  '/showcase/register': typeof ShowcaseRegisterRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/hackathon': typeof HackathonRouteWithChildren
  '/highlights': typeof HighlightsRoute
  '/mascot': typeof MascotRoute
  '/mcp': typeof McpRoute
  '/n30': typeof N30Route
  '/project-exhibition': typeof ProjectExhibitionRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/showcase': typeof ShowcaseRouteWithChildren
  '/speakers': typeof SpeakersRoute
  '/sponsors': typeof SponsorsRoute
  '/venue': typeof VenueRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/n30-chat': typeof ApiN30ChatRoute
  '/hackathon/register': typeof HackathonRegisterRoute
  '/project-exhibition/register': typeof ProjectExhibitionRegisterRoute
  '/showcase/register': typeof ShowcaseRegisterRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/hackathon': typeof HackathonRouteWithChildren
  '/highlights': typeof HighlightsRoute
  '/mascot': typeof MascotRoute
  '/mcp': typeof McpRoute
  '/n30': typeof N30Route
  '/project-exhibition': typeof ProjectExhibitionRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/showcase': typeof ShowcaseRouteWithChildren
  '/speakers': typeof SpeakersRoute
  '/sponsors': typeof SponsorsRoute
  '/venue': typeof VenueRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/n30-chat': typeof ApiN30ChatRoute
  '/hackathon/register': typeof HackathonRegisterRoute
  '/project-exhibition/register': typeof ProjectExhibitionRegisterRoute
  '/showcase/register': typeof ShowcaseRegisterRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/hackathon'
    | '/highlights'
    | '/mascot'
    | '/mcp'
    | '/n30'
    | '/project-exhibition'
    | '/schedule'
    | '/showcase'
    | '/speakers'
    | '/sponsors'
    | '/venue'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/n30-chat'
    | '/hackathon/register'
    | '/project-exhibition/register'
    | '/showcase/register'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/hackathon'
    | '/highlights'
    | '/mascot'
    | '/mcp'
    | '/n30'
    | '/project-exhibition'
    | '/schedule'
    | '/showcase'
    | '/speakers'
    | '/sponsors'
    | '/venue'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/n30-chat'
    | '/hackathon/register'
    | '/project-exhibition/register'
    | '/showcase/register'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/hackathon'
    | '/highlights'
    | '/mascot'
    | '/mcp'
    | '/n30'
    | '/project-exhibition'
    | '/schedule'
    | '/showcase'
    | '/speakers'
    | '/sponsors'
    | '/venue'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/n30-chat'
    | '/hackathon/register'
    | '/project-exhibition/register'
    | '/showcase/register'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  HackathonRoute: typeof HackathonRouteWithChildren
  HighlightsRoute: typeof HighlightsRoute
  MascotRoute: typeof MascotRoute
  McpRoute: typeof McpRoute
  N30Route: typeof N30Route
  ProjectExhibitionRoute: typeof ProjectExhibitionRouteWithChildren
  ScheduleRoute: typeof ScheduleRoute
  ShowcaseRoute: typeof ShowcaseRouteWithChildren
  SpeakersRoute: typeof SpeakersRoute
  SponsorsRoute: typeof SponsorsRoute
  VenueRoute: typeof VenueRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiN30ChatRoute: typeof ApiN30ChatRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venue': {
      id: '/venue'
      path: '/venue'
      fullPath: '/venue'
      preLoaderRoute: typeof VenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers': {
      id: '/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof SpeakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-exhibition': {
      id: '/project-exhibition'
      path: '/project-exhibition'
      fullPath: '/project-exhibition'
      preLoaderRoute: typeof ProjectExhibitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n30': {
      id: '/n30'
      path: '/n30'
      fullPath: '/n30'
      preLoaderRoute: typeof N30RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mascot': {
      id: '/mascot'
      path: '/mascot'
      fullPath: '/mascot'
      preLoaderRoute: typeof MascotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highlights': {
      id: '/highlights'
      path: '/highlights'
      fullPath: '/highlights'
      preLoaderRoute: typeof HighlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hackathon': {
      id: '/hackathon'
      path: '/hackathon'
      fullPath: '/hackathon'
      preLoaderRoute: typeof HackathonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/register': {
      id: '/showcase/register'
      path: '/register'
      fullPath: '/showcase/register'
      preLoaderRoute: typeof ShowcaseRegisterRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/project-exhibition/register': {
      id: '/project-exhibition/register'
      path: '/register'
      fullPath: '/project-exhibition/register'
      preLoaderRoute: typeof ProjectExhibitionRegisterRouteImport
      parentRoute: typeof ProjectExhibitionRoute
    }
    '/hackathon/register': {
      id: '/hackathon/register'
      path: '/register'
      fullPath: '/hackathon/register'
      preLoaderRoute: typeof HackathonRegisterRouteImport
      parentRoute: typeof HackathonRoute
    }
    '/api/n30-chat': {
      id: '/api/n30-chat'
      path: '/api/n30-chat'
      fullPath: '/api/n30-chat'
      preLoaderRoute: typeof ApiN30ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HackathonRouteChildren {
  HackathonRegisterRoute: typeof HackathonRegisterRoute
}

const HackathonRouteChildren: HackathonRouteChildren = {
  HackathonRegisterRoute: HackathonRegisterRoute,
}

const HackathonRouteWithChildren = HackathonRoute._addFileChildren(
  HackathonRouteChildren,
)

interface ProjectExhibitionRouteChildren {
  ProjectExhibitionRegisterRoute: typeof ProjectExhibitionRegisterRoute
}

const ProjectExhibitionRouteChildren: ProjectExhibitionRouteChildren = {
  ProjectExhibitionRegisterRoute: ProjectExhibitionRegisterRoute,
}

const ProjectExhibitionRouteWithChildren =
  ProjectExhibitionRoute._addFileChildren(ProjectExhibitionRouteChildren)

interface ShowcaseRouteChildren {
  ShowcaseRegisterRoute: typeof ShowcaseRegisterRoute
}

const ShowcaseRouteChildren: ShowcaseRouteChildren = {
  ShowcaseRegisterRoute: ShowcaseRegisterRoute,
}

const ShowcaseRouteWithChildren = ShowcaseRoute._addFileChildren(
  ShowcaseRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  HackathonRoute: HackathonRouteWithChildren,
  HighlightsRoute: HighlightsRoute,
  MascotRoute: MascotRoute,
  McpRoute: McpRoute,
  N30Route: N30Route,
  ProjectExhibitionRoute: ProjectExhibitionRouteWithChildren,
  ScheduleRoute: ScheduleRoute,
  ShowcaseRoute: ShowcaseRouteWithChildren,
  SpeakersRoute: SpeakersRoute,
  SponsorsRoute: SponsorsRoute,
  VenueRoute: VenueRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiN30ChatRoute: ApiN30ChatRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
